package com.ade.exp.cayenne.base.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Country was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Country extends CayenneDataObject {

    public static final String CODE_PROPERTY = "code";
    public static final String NAME_PROPERTY = "name";

    public static final String ID_PK_COLUMN = "ID";

    public void setCode(Integer code) {
        writeProperty(CODE_PROPERTY, code);
    }
    public Integer getCode() {
        return (Integer)readProperty(CODE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

}
